### ISSUE TITLE
I tried to run abnormally in docker running in host network mode.

### ISSUE THREAD

**Issue by zengqinglei** [ctripcorp/apollo.net#18]
* Base framework: .Net Core  2.1.2
* Running environment: Centos 7 or ubuntu 18.04 、docker 18.06.0-ce

* Exception
```
Unhandled Exception: System.InvalidOperationException: Failed to create instance of type 'Com.Ctrip.Framework.Apollo.ApolloOptions'. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Com.Ctrip.Framework.Apollo.Foundation.NetworkInterfaceManager' threw an exception. ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
at System.Net.Dns.InternalGetHostByName(String hostName)
at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
at Com.Ctrip.Framework.Apollo.Foundation.NetworkInterfaceManager.Refresh()
at Com.Ctrip.Framework.Apollo.Foundation.NetworkInterfaceManager..cctor()
--- End of inner exception stack trace ---
at Com.Ctrip.Framework.Apollo.Foundation.NetworkInterfaceManager.get_HostIp()
at Com.Ctrip.Framework.Apollo.ApolloOptions..ctor()
--- End of inner exception stack trace ---
at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type)
--- End of inner exception stack trace ---
at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type)
at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
at Microsoft.Extensions.Configuration.ConfigurationBinder.Get(IConfiguration configuration, Type type, Action`1 configureOptions)
at Microsoft.Extensions.Configuration.ConfigurationBinder.Get[T](IConfiguration configuration, Action`1 configureOptions)
at Microsoft.Extensions.Configuration.ConfigurationBinder.Get[T](IConfiguration configuration)
at FabricDemo.UserService.Program.<>c.<CreateWebHostBuilder>b__1_0(WebHostBuilderContext hostingContext, IConfigurationBuilder builder) in /src/src/FabricDemo.UserService/Program.cs:line 25
at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at FabricDemo.UserService.Program.Main(String[] args) in /src/src/FabricDemo.UserService/Program.cs:line 15
```

*  with the following the steps to reproduce:
1. appsettings.json
```csharp
{
  "apollo": {
    "AppId": "FabricDemo.UserService",
    "MetaServer": "http://pro.meta-server.zengql.local"
  }
}
```
2. program.cs
```csharp
/// <inheritdoc />
public class Program
{
	/// <inheritdoc />
	public static void Main(string[] args)
	{
		CreateWebHostBuilder(args).Build().Run();
	}

	/// <inheritdoc />
	public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
		WebHost.CreateDefaultBuilder(args)
			.ConfigureAppConfiguration(
				(hostingContext, builder) =>
				{
					builder.AddApollo(builder.Build().GetSection("apollo"))
						.AddDefault()
						.AddNamespace("TEST1.ConsulPublic");
				})
			.UseStartup<Startup>();
}
```
3. dockerfile
```
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 54045

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY src/FabricDemo.UserService/FabricDemo.UserService.csproj src/FabricDemo.UserService/
RUN dotnet restore src/FabricDemo.UserService/FabricDemo.UserService.csproj
COPY . .
WORKDIR /src/src/FabricDemo.UserService
RUN dotnet build FabricDemo.UserService.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish FabricDemo.UserService.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "FabricDemo.UserService.dll"]
```
4. docker-compose.yml
```
version: '3'

services:
  userservice:
    container_name: userservice
    image: fabricdemo/userservice:${TAG:-latest}
    build:
      context: .
      dockerfile: src/FabricDemo.UserService/Dockerfile
    network_mode: host
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://127.0.0.1:54045
    ports:
      - "54045:54045"
```

Start command: docker-compose up --build

**_Please give a solution, thanks!_**

**Comment by linkinshi** [comment]
1. add "LocalIp"  
"apollo": {
    "AppId": "lzb",
    "Env": "Dev",
    "MetaServer": "http://192.168.1.86:9080",
    "LocalIp": "192.168.1.120"
  }
2. setting the "hostname" in /etc/hosts

**Comment by zengqinglei** [comment]
@linkinshi 嗯，是的，加我微信呗：liger_zql

**Comment by nobodyiam** [comment]
请参考 https://github.com/ctripcorp/apollo/issues/1376 中的解决方案。

**Comment by pengweiqhca** [comment]
@zengqinglei [已加try catch](https://github.com/ctripcorp/apollo.net/pull/19/commits/33d8d86fa4605b3399aca85e479ac791863835ab#diff-9342fe5390630148a0043622a62fbf21)

**Comment by zengqinglei** [comment]
@pengweiqhca 
#### 由于我这两天使用比较急，所以根据官方API开发.net standard 类库，已开源！

#### 下面是我改写的IP地址获取方式：

> [新的获取IP地址方式](https://github.com/zengqinglei/Creekdream.Configuration.Apollo/blob/2d80de026af8badf458123edca9ed46851d14c7c/src/Creekdream.Configuration.Apollo/ApolloConfigurationProvider.cs#L139)

_上面这种方式docker部署以_ host或bridge 网络模式运行均能正常获取IP，看看是否可以调整成这种方式！

### 非常感谢你们！
